#ifndef XMLCC_DETAIL_CONFIG_HXX
#define XMLCC_DETAIL_CONFIG_HXX

#cmakedefine XMLXX_CXX11

#cmakedefine XMLXX_CXX14

#cmakedefine XMLXX_CXX17

#cmakedefine XMLXX_NO_EXCEPTIONS

#cmakedefine XMLCC_USE_EXTERNAL_EXPAT

#cmakedefine XMLCC_USE_EXTERNAL_GENX

#endif // !XMLCC_DETAIL_CONFIG_HXX
