#ifndef XMLCC_DETAIL_CONFIG_VC_H
#define XMLCC_DETAIL_CONFIG_VC_H

#define XMLCC_CXX11

#define XMLCC_CXX14

#define XMLCC_CXX17

// #undef XMLCC_NO_EXCEPTIONS

// #undef XMLCC_USE_EXTERNAL_EXPAT

// #undef XMLCC_USE_EXTERNAL_GENX

// #undef XMLCC_STATIC_LIB

#endif // !XMLCC_DETAIL_CONFIG_VC_H
