#ifndef XMLCC_DETAIL_CONFIG_HXX
#define XMLCC_DETAIL_CONFIG_HXX

#cmakedefine XMLCC_CXX11

#cmakedefine XMLCC_CXX14

#cmakedefine XMLCC_CXX17

#cmakedefine XMLCC_NO_EXCEPTIONS

#cmakedefine XMLCC_USE_EXTERNAL_EXPAT

#cmakedefine XMLCC_USE_EXTERNAL_GENX

#endif // !XMLCC_DETAIL_CONFIG_HXX
