#ifndef XMLCC_DETAIL_CONFIG_VC_H
#define XMLCC_DETAIL_CONFIG_VC_H

#define XMLXX_CXX11

#define XMLXX_CXX14

#define XMLXX_CXX17

// #undef XMLXX_NO_EXCEPTIONS

// #undef XMLCC_USE_EXTERNAL_EXPAT

// #undef XMLCC_USE_EXTERNAL_GENX

// #undef XMLCC_STATIC_LIB

#endif // !XMLCC_DETAIL_CONFIG_VC_H
